version: '3.8'

networks:
  gic-network:
    name: Global-Identity-Centre
    driver: bridge

services:
  # Application Container
  app:
    container_name: {{DEPLOY_NAME}}-app
    image: {{DOCKER_IMAGE}}
    networks:
      - gic-network
#    restart: always
    tty: true
    ports:
      - '80:80'
#      - '443:443'
    volumes:
      - ./web:/var/www/html:rw
      - ./logs:/var/log/nginx:rw
#      - ./config/.env:/var/www/html/.env:rw
#      - ./xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:rw
#    command: /bin/sh -c "php artisan l5-swagger:generate > /dev/null"
