#FROM webdevops/php-nginx:8.0-alpine
FROM php:fpm-alpine3.14
LABEL Maintainer="Ihor Porokhnenko <ihor.porokhnenko@gmail.com>"
LABEL Description="Lightweight container with Nginx & PHP-FPM 8 based on Alpine Linux."

# Do a single run command to make the intermediary containers smaller.
#RUN set -ex

## Update package list
RUN apk update

## Install packages necessary during the build phase
RUN apk --no-cache add \
    mc \
    nano \
    nginx

## Install PHP extensions Installer package
ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/
RUN chmod +x /usr/local/bin/install-php-extensions

## Install composer
RUN install-php-extensions \
    @composer \
    pdo_mysql

## Clean apk cache after all installed packages
RUN rm -rf /var/cache/apk/*


#RUN /bin/sh -c rm /etc/nginx/conf.d/default.conf

#EXPOSE 80 443
#CMD ["nginx", "-g", "daemon off;"]
